language: node_js
node_js:
  - 8
  - 10
  - 12
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
    - os: osx
cache:
  yarn: true
  directories:
    - node_modules
install:
  - npm install -g yarn
  - npm install -g lerna
  - yarn bootstrap
script:
  - yarn build
  - yarn test
after_script:
  - yarn coveralls
