language: node_js
os:
  - linux
node_js:
  - 8
  - 10
  - 12
addons:
  apt:
    packages:
      - xvfb
cache:
  yarn: true
  directories:
    - node_modules
install:
  - npm install -g yarn
  - npm install -g lerna
  - yarn bootstrap
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sleep 3; fi
script:
  - yarn build
  - yarn test
after_script:
  - yarn coveralls
