name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm install -g yarn
        npm install -g lerna
    - name: yarn bootstrap
      run: |
        yarn bootstrap
    - name: yarn build and test
      run: |
        yarn build
        yarn test
    - name: yarn coveralls
      run: |
        yarn coveralls
