name: 🤝　Contributors
on:
  schedule:
    - cron: '0 1 * * *'
  push:
    branches:
      - master
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: bubkoo/use-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          env_name: bot_token
      - uses: bubkoo/contributors-list@v1
        with:
          GITHUB_TOKEN: ${{ env.bot_token }}
          svgPath: CONTRIBUTORS.svg
          commitMessage: chore: update CONTRIBUTORS [skip ci]
