name: 💡　Coveralls

on:
  workflow_call:
    inputs:
      pkg:
        required: true
        type: string

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./packages/${{ inputs.pkg }}/test/coverage/lcov.info
        flags: ${{ inputs.pkg }}
