name: 🎉　Rebase
on:
  issue_comment:
    types: [created]
jobs:
  run:
    steps:
      - uses: actions/checkout@master
      - uses: cirrus-actions/rebase@master
        env:
          GITHUB_TOKEN: ${{ secrets.bot_token }}
