name: 🔱　Slash Commands
on:
  issue_comment:
    types: [created]
jobs:
  run:
    steps:
      - uses: bubkoo/slash-commands@v1
        with:
          GITHUB_TOKEN: ${{ secrets.bot_token }}
          CONFIG_FILE: .github/workflows/config/slash-commands.yml
