name: 🎗　Update Authors
on:
  push:
    branches:
      - master
      - next
      - next-major
      - alpha
      - beta
jobs:
  authors:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/use-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          env_name: bot_token
      - uses: wow-actions/update-authors@v1
        with:
          GITHUB_TOKEN: ${{ env.bot_token  }}
          path: CONTRIBUTORS
          bots: false
